---
## Helm install
# Helm version to install
helm_version: v3.10.2

# Donwload url of helm(is completely blocked in China) Using huaweicloud helm mirror instead
# see more discussion about it at: https://github.com/helm/helm/issues/7028
# helm_download_url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
helm_download_url: https://repo.huaweicloud.com/helm/{{ helm_version }}/helm-{{ helm_version }}-linux-amd64.tar.gz

# Download url of helm(aliyun mirror)
# helm_download_mirror_url: 

# Location to download helm arch
helm_download_dir: /usr/local

# Name of downloaded helm
helm_file_name: helm-{{helm_version}}-linux-amd64.tar.gz

# Unarchive helm.tar.gz helm file loacation
helm_exector_file_dir: "{{helm_download_dir}}/linux-amd64"

# Location to install helm
helm_install_dir: /usr/local/bin

## Install kubediag using helm(Temporarily abandoned the method)
kubediag_repo: https://kubediag.github.io/kubediag-helm

# Default chart and release name
kubediag_chart_release_name: kubediag

## Deploy kubediag
# Namespace of cert manager is installed
cert_manager_ns: cert-manager

# Location of config/deploy
kubediag_deploy_dir: "{{kubediag_dir}}/config/deploy"

# kubediag default namepace 
kubediag_namespace: kubediag


