---
- name: Execute `systemctl daemon-reload` to reload kubediag.service
  become: yes
  command: systemctl daemon-reload

- name: Checking file kubediag.service on ubuntu
  stat:
    path: /etc/systemd/system/kubediag.service
  register: ubuntu_kubediag_service

- name: Checking file kubediag.service on CentOS
  stat: 
    path: /usr/lib/systemd/system/kubediag.service
  register: centos_kubediag_service

- name: Execute `systemctl start kubediag` to start kubediag service
  become: yes
  command: systemctl start kubediag
  when: ubuntu_kubediag_service.stat.exists or centos_kubediag_service.stat.exists

- name: Enable kubediag.service
  become: yes
  command: systemctl enable kubediag
  when: ubuntu_kubediag_service.stat.exists or centos_kubediag_service.stat.exists

## kubediag-master service
- name: Checking file kubediag-master.service on ubuntu
  stat:
    path: /etc/systemd/system/kubediag-master.service
  register: ubuntu_kubediag_master_service

- name: Checking file kubediag-master.service on CentOS
  stat: 
    path: /usr/lib/systemd/system/kubediag-master.services
  register: centos_kubediag_master_service

- name: Start kubediag-master service
  become: yes
  command: systemctl start kubediag-master
  when: ubuntu_kubediag_master_service.stat.exists or centos_kubediag_master_service.stat.exists

- name: Enable kubediag-master.service
  become: yes
  command: systemctl enable kubediag-master
  when: ubuntu_kubediag_master_service.stat.exists or centos_kubediag_master_service.stat.exists