---
## Parameters about base environment installation
# Docker version
docker_verion_ubuntu: 5:20.10.15~3-0

# K3s server version
K3s_server_version: v1.20.15+k3s1

## kubediag_deploy location that copying to agent nodes
# kubediag location on agent nodes
kubediag_agent_dir: ~/kubediag

## Parameters about KubeDiag startup settings
# KubeDiag is running as an agent
Mode: agent

# KubeDiag server on 8090 port
Port: 8090

# NodeName 
NodeName: node

# The port the metric endpoint to serve on
MetricsPort: 10357

# Root directory of persistent kubediag data
DataRoot: /var/lib/kubediag

# The main template file for running python3 function
Python3MainFilePath: "{{ DataRoot }}/function-main"

