---
## kubediag_deploy location that copying to agent nodes
# kubediag location on agent nodes
kubediag_agent_dir: ~/kubediag

## Parameters about kubediag master service settings
# kubediag is running as a master
master_Mode: master

# kubediag server on 8090 port
master_Port: 8089

# The port the metric endpoint to serve on
master_MetricsPort: 10357

# FIXME:master node enable-leader-election
master_EnableLeaderElection: false

## Parameters about kubediag agent serivce settings
# kubediag is running as an agent
Mode: agent

# kubediag server on 8090 port
Port: 8090

# NodeName 
NodeName: node

# The port the metric endpoint to serve on
MetricsPort: 10355

# Root directory of persistent kubediag data
DataRoot: /var/lib/kubediag

# The main template file for running python3 function
Python3MainFilePath: "{{ DataRoot }}/function-main"

