---
## Send kubediag exec、kubediag.service and kubediag env file to specified directory

# kubediag executable file
- name: Chmod +x for kubediag exec
  file: 
    path: "{{ exec_in_service_agent }}"
    mode: '0755'

# kubediag parameters file for systemd
- name: Chmod +r for kubediag.service
  file: 
    path: "{{ service_in_kubediag_agent }}"
    mode: '0644'

# kubediag service file for systemd
- name: Chmod +r for kubediag
  file: 
    path: "{{ para_service_in_kubediag_agent }}"
    mode: '0644'

# python3 template file for construct function
- name: Chmod +r for python3 file
  file:
    path: "{{ python3_in_kubediag_agent }}"
    mode: '0644'

# Distribute file to specific directory from all.yml on agent nodes
- name: Copying kubediag exec file to {{ kubediag_exec }}
  become: yes
  command: cp -f {{ exec_in_service_agent }} {{ kubediag_exec }}

## kubediag.service
# Ubuntu
- name: Copying kubediag.service file to {{ kubediag_service }}
  become: yes
  command: cp -f {{ service_in_kubediag_agent }} {{ kubediag_service }}
  when: ansible_distribution == "Ubuntu"

# CentOS
- name: Copying kubediag.service file to /usr/lib/systemd/system
  become: yes
  command: cp -f {{ service_in_kubediag_agent }} /usr/lib/systemd/system
  when: ansible_distribution == "CentOS"

## environmentfile
# Ubuntu
- name: Copying kubediag env file to /etc/default
  become: yes
  command: cp -f {{ para_service_in_kubediag_agent }} /etc/default
  when: ansible_distribution == "Ubuntu"

# Centos
- name: Copying kubediag env file to /etc/sysconfig
  become: yes
  command: cp -f {{ para_service_in_kubediag_agent }} /etc/sysconfig
  when: ansible_distribution == "CentOS"

## Python3 main file template 
- name: Checking python3 main file template directory is exist
  stat: 
    path: "{{ Python3MainFilePath }}"
  register: python3_stat

- name: Create python3 directory if not exist
  file:
    path: "{{ Python3MainFilePath }}"
    state: directory
    mode: '0755'
  when: not python3_stat.stat.exists

- name: Copying python3 main file template to {{ Python3MainFilePath }}
  command: cp -f {{ python3_in_kubediag_agent }} {{ Python3MainFilePath }}
