---
# Install k3s on control plane(k3s-server host)
- name: Create directory to save images
  become: yes
  file:
    path: /var/lib/rancher/k3s/agent/images
    state: directory
    mode: '0755'

- name: Copying images tar to /var/lib/rancher/k3s/agent/images
  become: yes
  command: cp -f {{ k3s_images_file }} /var/lib/rancher/k3s/agent/images

- name: Copying k3s exec bin to /usr/local/bin
  become: yes
  command: cp -f {{ k3s_exec_bin }} /usr/local/bin

- name: Chmod +x for K3s exec binary
  become: yes
  file:
    path: /usr/local/bin/k3s
    mode: '0755'

- name: Chmod +x for installation script
  become: yes
  file: 
    path: "{{ k3s_install_script }}"
    mode: '0755'

- name: Executing install.sh script to install K3s
  become: yes
  shell: INSTALL_K3S_SKIP_DOWNLOAD=true sh {{ k3s_install_script }}

- name: Verifying K3s is installed successfully
  stat: 
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_config_stat

- name: Printing message that K3s is installed successfully
  debug:
    msg: "K3s is installed successfully on airgap environment"
  when: k3s_config_stat.stat.exists
  
