---
## Not use docker but containerd that k3s use default
# - include_tasks: install_docker.yml

- include_tasks: install_k3s.yml

# Copy /etc/rancher/k3s/k3s.yaml to .kube/config
- include_tasks: copy_config.yml

# Verify the installation of k3s using `kubectl get node`
- include_tasks: verify_kubectl_k3s.yml
