---
- name: Verifying k3s is working normally
  command: kubectl get node
  register: contents

- name: Exiting playbook because some error
  debug:
    msg: "K3s get node info successfully"

- name: Waiting and checking K3s node is Ready status
  command: kubectl get node -o json
  register: node_info
  retries: 30
  delay: 3
  until: node_info.stdout|from_json|json_query('items[0].status.conditions[?type==`Ready`].status') == ['True']

- name: K3s node is Ready status
  debug:
    msg: k3s node is Ready status
