# Copy k3s's config file(~/.kube/config) to kubediag, and distribute this directory directlly
- name: Create k3s directory in kubediag directory if not exist
  file:
    path: "{{ config_in_kubediag }}"
    state: directory
    mode: '0755'
    
- name: Copying config file to kubediag/k3s directory
  command: cp -pf ~/.kube/config {{ config_in_kubediag }}/config

# 需要修改config文件中的server:https://127.0.0.1:6443为局域网地址，否则无法访问集群
- name: Modify server ip of config file for APIServer
  lineinfile:
    path: "{{ config_in_kubediag }}/config"
    regexp: '\s*server:'
    # 4 spaces
    line: '    server: https://{{ansible_ssh_host}}:6443'
