---
- name: Install kubectl on k3s-server
  hosts: k3s-server
  vars:
    kubectl_version: v1.20.15
    download_url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    kubectl_location: /usr/local/bin
  gather_facts: no
  become: no
  tasks:
  - name: Check whether kubectl has been installed
    command: kubectl
    register: has_installed
    ignore_errors: true

  - name: Print kubectl version
    debug: 
      msg: "kubectl has been installed, so it will not be installed again, all task of install kubectl left will skipped"
    when: "has_installed.rc == 0"
  
  - name: Install kubectl and ensure install success
    block:
      # Install kubectl(v1.20.15)
      - name: Start install kubectl
        command: curl -L {{ download_url }} -o {{ kubectl_location }}/kubectl

      - name: confirm kubectl downloaded
        shell: ls {{ kubectl_location }} | grep kubectl
        register: kubectl_exist

      - name: Chmod +x kubectl
        file:
          path: "{{ kubectl_location }}/kubectl"
          mode: '0777'
        when: "'kubectl' == kubectl_exist.stdout"

      - name: kubectl install failed
        debug:
          msg: "kubectl install failed"
        when: kubectl_exist.stdout == ""
      
      - name: Ensure kubectl installed
        command: kubectl
        register: ret
        ignore_errors: true
      
      - name: Print error message
        debug:
          msg: "kubectl install failed"
        when: "ret.rc != 0"

      - name: Print kubectl version
        debug:
          msg: "kubectl install successed"
        when: "ret.rc == 0"
    when: "has_installed.rc != 0"
