## Parameters about kubediag.service by systemd manager
# Location of kubediag exec file
exec_in_service_agent: "{{ kubediag_agent_dir }}/kubediag/kubediag"

# Location to save systemd service file of kubediag(must inside kubediag directory)
service_in_kubediag_agent: "{{ kubediag_agent_dir }}/kubediag/service/kubediag.service"

# File that save kubediag.service parameters
para_service_in_kubediag_agent: "{{ kubediag_agent_dir }}/kubediag/service/kubediag"

# Python3 main template file
python3_in_kubediag_agent: "{{ kubediag_agent_dir }}/kubediag/python3/python3"