---
## File path of kubediag directory
# Location to save kubediag directory on k3s node
kubediag_dir: "{{ lookup('ansible.builtin.env', 'PWD') }}/kubediag"

# Location of config/deploy
kubediag_deploy_dir: "{{ kubediag_dir }}/config/deploy"

# Location to save config for distribution(must inside kubediag directory)
config_in_kubediag: "{{ kubediag_dir }}/k3s"

# Location of service
service_dir: "{{ kubediag_dir }}/service"

# Location of kubediag exec file
exec_in_service: "{{ kubediag_dir }}/kubediag"

# Location to save systemd service file of kubediag(must inside kubediag directory)
service_in_kubediag: "{{ kubediag_dir }}/service/kubediag.service"

# File that save kubediag service parameters
para_service_in_kubediag: "{{ kubediag_dir }}/service/kubediag"

# Location to save systemd service file of kubediag master(must inside kubediag directory)
master_service_in_kubediag: "{{ kubediag_dir }}/service/kubediag-master.service"

# Location to save kubediag-master service parameters
master_para_service_in_kubediag: "{{ kubediag_dir }}/service/kubediag-master"

## Cert Manager installation
# Cert Manager version
cert_manager_version: v1.0.4

# Cert manager yaml file path
cert_manager_file_path: "{{ kubediag_dir }}/cert-manager/cert-manager.yaml"

## K3s installation 
# k3s exec location in kubediag
k3s_exec_bin: "{{ kubediag_dir }}/k3s/k3s"

# k3s images location in kubediag
k3s_images_file: "{{ kubediag_dir }}/images/k3s-airgap-images-amd64.tar"

# installation script location in kubediag
k3s_install_script: "{{ kubediag_dir }}/install.sh"

# images directory
images_dir: "{{ kubediag_dir }}/images"

