---
## 
# Location to save config for distribution(must inside kubediag directory)
config_in_kubediag: "{{ kubediag_dir }}/k3s"

# Location of service
service_dir: "{{ kubediagdir }}/service"

# Location of kubediag exec file
exec_in_service: "{{ kubediag_dir }}/kubediag"

# Location to save systemd service file of kubediag(must inside kubediag directory)
service_in_kubediag: "{{ kubediag_dir }}/service/kubediag.service"

# File that save kubediag.service parameters
para_service_in_kubediag: "{{ kubediag_dir }}/service/kubediag"





